version: "2.0"

services:
    music:
      image: music
      build:
        context: .
      depends_on:
        - db
      ports:
        - 80:8000
      links:
        - db
    
    db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=prithivi
        - POSTGRES_PASSWORD=Jaya@12
      ports:
        - '5432:5432'
      volumes: 
        - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
