# Generated by Django 4.1.3 on 2022-12-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app_apis', '0002_destination_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
