# Generated by Django 4.1.3 on 2022-12-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app_apis', '0004_remove_destination_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
