# Generated by Django 4.1.3 on 2023-03-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app_apis', '0005_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
