# Generated by Django 4.1.3 on 2023-03-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_app_apis', '0006_delete_destination_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSongs',
            fields=[
                ('song_name', models.CharField(max_length=255)),
                ('song_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('overall_song_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SongRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_rating', models.IntegerField()),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app_apis.allsongs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app_apis.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_user_id', models.CharField(max_length=255)),
                ('recommendation_to', models.CharField(max_length=255)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app_apis.allsongs')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=255)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app_apis.allsongs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app_apis.userinfo')),
            ],
        ),
    ]
