# Generated by Django 4.1.3 on 2023-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app_apis', '0008_alter_userinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsongs',
            name='song_id_new',
            field=models.IntegerField(null=True),
        ),
    ]
